version: '3'

services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    image: hkb-docusaurus
    container_name: hkb-docusaurus
    ports:
      - 3000:3000
    volumes:
      - ./website:/app/
